### ISSUE TITLE
Screen rolling on latest 120MHz ram / flash

### ISSUE THREAD

**Issue by bwhitman** [shorepine/tulipcc#112]
I am seeing screen rolling (like bad-v-sync) on the latest main Tulip CC running an example like `parallax.py`. It seems to be an interaction between flash reads and display writes. If i do `tulip.display_stop()` before the disk loads and turn it back on before the game start, everything is fine. This seems like new behavior since last week, so i'll have to track this down with a git bisect.

**Comment by bwhitman** [comment]
Same for `planet_boing`, which i know for sure was 100% stable last friday (june 30). I'll start looking at commits around this one https://github.com/bwhitman/tulipcc/commit/27ab279e7cf2df8bdc1acf32ccc3ebc20945bd86 and later

**Comment by bwhitman** [comment]
This was ridiculous and took me too much time to find. The bad commit was this one https://github.com/bwhitman/tulipcc/commit/d2ae3001b032f84ca5b24d87a9c21a2c1d035a54

Can anyone else see it? I somehow copied all the important stuff into `sdkconfig.tulip` but missed the top line, the `CONFIG_EXPERIMENTAL_FEATURES`. So the builds were omitting that, which meant setting RAM/FLASH to 120 had no effect, which meant they were using their default, 40MHz, which is not enough to reliably draw a screen. ESP shows no compilation errors if you try to set an experimental feature without the flag on, just silently fails to set it and falls back to default.

**Comment by dpwe** [comment]
You faithfully copied the lines from [TULIP4_N8R8/sdkconfig.board](https://github.com/bwhitman/tulipcc/issues/112#diff-4625b11775a736da783b3fa3b19a3796d56bf43be651aa19bb676e0057bc6c13) which had already lost `CONFIG_IDF_EXPERIMENTAL_FEATURES`.  We must go deeper...
